import { useState, useMemo } from 'react';
import { useSupabaseData } from '../hooks/useSupabaseData';
import { toast } from 'sonner';

interface Story {
  id: string;
  title: string;
  description?: string;
  status: string;
  acceptanceCriteria?: string[];
  tags?: string[];
  moduleId?: string;
}

interface Module {
  id: string;
  name: string;
  riskLevel: string;
  defectFrequency: number;
  businessImpact: number;
  testingProtocol: string;
}

interface TestCase {
  id: string;
  title: string;
  description: string;
  type: string;
  steps: string[];
  expectedResults: string[];
  linkedStory?: string;
  status: string;
  priority: 'High' | 'Medium' | 'Low';
  moduleId?: string;
}

interface Bug {
  id: string;
  title: string;
  linkedStory?: string;
  severity: string;
  status: string;
}

interface Recommendation {
  id: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  type: 'Coverage Gap' | 'Risk-Based' | 'Regression' | 'New Feature' | 'Bug Pattern';
  storyId?: string;
  storyTitle?: string;
  moduleId?: string;
  moduleName?: string;
  reason: string;
  suggestedTests: string[];
  estimatedEffort: string;
  autoGenerated: boolean;
}

interface TestRecommendationsProps {
  onNavigate?: (tab: string, itemId?: string) => void;
}

export function TestRecommendations({ onNavigate }: TestRecommendationsProps) {
  const [filterPriority, setFilterPriority] = useState<string>('all');
  const [filterType, setFilterType] = useState<string>('all');
  const [showAutoOnly, setShowAutoOnly] = useState(false);
  const [expandedRecs, setExpandedRecs] = useState<Set<string>>(new Set());
  const [dismissedRecs, setDismissedRecs] = useState<Set<string>>(new Set());
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [previewTestCases, setPreviewTestCases] = useState<TestCase[]>([]);

  const { data: stories } = useSupabaseData<Story[]>('aqms_stories', []);
  const { data: modules } = useSupabaseData<Module[]>('aqms_modules', []);
  const { data: testCases, setData: setTestCases } = useSupabaseData<TestCase[]>('aqms_test_cases', []);
  const { data: bugs } = useSupabaseData<Bug[]>('aqms_bugs', []);

  const recommendations = useMemo(() => {
    const recs: Recommendation[] = [];
    let recId = 1;

    // 1. Coverage Gap Analysis - Stories without tests
    stories
      .filter(s => !testCases.some(tc => tc.linkedStory === s.id))
      .forEach(story => {
        recs.push({
          id: `REC-${recId++}`,
          priority: story.status === 'In Testing' || story.status === 'Ready for Dev' ? 'High' : 'Medium',
          type: 'Coverage Gap',
          storyId: story.id,
          storyTitle: story.title,
          reason: `Story has no linked test cases. Current status: ${story.status}`,
          suggestedTests: [
            `Functional test: Verify ${story.title} basic functionality`,
            `Integration test: Test ${story.title} with dependent components`,
            story.acceptanceCriteria && story.acceptanceCriteria.length > 0
              ? `Acceptance test: Validate all ${story.acceptanceCriteria.length} acceptance criteria`
              : 'Acceptance test: Validate acceptance criteria',
          ],
          estimatedEffort: '2-4 hours',
          autoGenerated: true,
        });
      });

    // 2. Risk-Based Testing - High risk modules without regression tests
    modules
      .filter(m => m.riskLevel === 'High')
      .forEach(module => {
        const moduleStories = stories.filter(s => s.moduleId === module.id);
        const storyIds = new Set(moduleStories.map(s => s.id));
        const moduleTestCases = testCases.filter(tc => 
          tc.moduleId === module.id || (tc.linkedStory && storyIds.has(tc.linkedStory))
        );
        const regressionTests = moduleTestCases.filter(tc => tc.type === 'Regression');
        if (regressionTests.length < 3) {
          recs.push({
            id: `REC-${recId++}`,
            priority: 'Critical',
            type: 'Risk-Based',
            moduleId: module.id,
            moduleName: module.name,
            reason: `High-risk module (Defect Freq: ${module.defectFrequency}/10, Impact: ${module.businessImpact}/10) requires comprehensive regression coverage`,
            suggestedTests: [
              `Regression suite: Core ${module.name} functionality`,
              `Edge case testing: Boundary conditions in ${module.name}`,
              `Performance test: ${module.name} under load`,
              `Security test: Authentication/authorization in ${module.name}`,
            ],
            estimatedEffort: '6-8 hours',
            autoGenerated: true,
          });
        }
      });

    // 3. Bug Pattern Analysis - Stories with recurring bugs
    const storiesWithMultipleBugs = stories.filter(story => {
      const linkedBugs = bugs.filter(b => b.linkedStory === story.id);
      return linkedBugs.length >= 2;
    });

    storiesWithMultipleBugs.forEach(story => {
      const storyBugs = bugs.filter(b => b.linkedStory === story.id);
      const criticalBugs = storyBugs.filter(b => b.severity === 'Critical');

      recs.push({
        id: `REC-${recId++}`,
        priority: criticalBugs.length > 0 ? 'Critical' : 'High',
        type: 'Bug Pattern',
        storyId: story.id,
        storyTitle: story.title,
        reason: `Story has ${storyBugs.length} linked bugs (${criticalBugs.length} critical). Pattern indicates insufficient test coverage.`,
        suggestedTests: [
          `Regression test: Reproduce conditions that caused previous bugs`,
          `Negative testing: Validate error handling and edge cases`,
          `Exploratory testing session: Uncover additional defects`,
          `Code review-based tests: Cover complex logic branches`,
        ],
        estimatedEffort: '4-6 hours',
        autoGenerated: true,
      });
    });

    // 4. Regression Testing - Recent bug fixes need regression tests
    const recentlyResolvedBugs = bugs.filter(
      b => (b.status === 'Resolved' || b.status === 'Closed') && b.linkedStory
    );

    const storiesWithResolvedBugs = Array.from(
      new Set(recentlyResolvedBugs.map(b => b.linkedStory))
    ).map(storyId => stories.find(s => s.id === storyId)).filter(Boolean) as Story[];

    storiesWithResolvedBugs.forEach(story => {
      const hasRegressionTest = testCases.some(
        tc => tc.linkedStory === story.id && tc.type === 'Regression'
      );

      if (!hasRegressionTest) {
        recs.push({
          id: `REC-${recId++}`,
          priority: 'High',
          type: 'Regression',
          storyId: story.id,
          storyTitle: story.title,
          reason: 'Story had bugs that were resolved. Add regression tests to prevent recurrence.',
          suggestedTests: [
            'Regression test: Verify bug fix remains stable',
            'Smoke test: Ensure related functionality not broken',
            'Integration test: Validate fix in end-to-end scenarios',
          ],
          estimatedEffort: '2-3 hours',
          autoGenerated: true,
        });
      }
    });

    // 5. New Feature Testing - Stories in development
    stories
      .filter(s => s.status === 'In Development' || s.status === 'Ready for Dev')
      .filter(s => testCases.filter(tc => tc.linkedStory === s.id).length < 2)
      .forEach(story => {
        recs.push({
          id: `REC-${recId++}`,
          priority: 'Medium',
          type: 'New Feature',
          storyId: story.id,
          storyTitle: story.title,
          reason: `Story is in development (${story.status}) with minimal test coverage. Plan tests early.`,
          suggestedTests: [
            `Unit test: Test individual components of ${story.title}`,
            `Integration test: Verify ${story.title} works with existing features`,
            `UI/UX test: Validate user experience and accessibility`,
          ],
          estimatedEffort: '3-5 hours',
          autoGenerated: true,
        });
      });

    // 6. Smoke Testing - Critical modules need smoke tests
    modules
      .filter(m => m.businessImpact >= 8)
      .forEach(module => {
        const moduleStories = stories.filter(s => s.moduleId === module.id);
        const storyIds = new Set(moduleStories.map(s => s.id));
        const moduleTestCases = testCases.filter(tc => 
          tc.moduleId === module.id || (tc.linkedStory && storyIds.has(tc.linkedStory))
        );
        const hasSmokeTests = moduleTestCases.some(tc => tc.type === 'Smoke');
        if (!hasSmokeTests) {
          recs.push({
            id: `REC-${recId++}`,
            priority: 'High',
            type: 'Risk-Based',
            moduleId: module.id,
            moduleName: module.name,
            reason: `Critical business impact (${module.businessImpact}/10) requires smoke test suite for rapid validation`,
            suggestedTests: [
              `Smoke test: ${module.name} basic health check`,
              `Smoke test: Critical path through ${module.name}`,
              `Smoke test: ${module.name} availability and responsiveness`,
            ],
            estimatedEffort: '1-2 hours',
            autoGenerated: true,
          });
        }
      });

    return recs;
  }, [stories, modules, testCases, bugs]);

  const filteredRecommendations = useMemo(() => {
    let filtered = recommendations.filter(r => !dismissedRecs.has(r.id));

    if (filterPriority !== 'all') {
      filtered = filtered.filter(r => r.priority === filterPriority);
    }

    if (filterType !== 'all') {
      filtered = filtered.filter(r => r.type === filterType);
    }

    if (showAutoOnly) {
      filtered = filtered.filter(r => r.autoGenerated);
    }

    return filtered.sort((a, b) => {
      const priorityOrder = { Critical: 0, High: 1, Medium: 2, Low: 3 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });
  }, [recommendations, filterPriority, filterType, showAutoOnly, dismissedRecs]);

  const metrics = useMemo(() => {
    return {
      total: recommendations.length,
      critical: recommendations.filter(r => r.priority === 'Critical').length,
      high: recommendations.filter(r => r.priority === 'High').length,
      medium: recommendations.filter(r => r.priority === 'Medium').length,
      low: recommendations.filter(r => r.priority === 'Low').length,
      byType: {
        coverageGap: recommendations.filter(r => r.type === 'Coverage Gap').length,
        riskBased: recommendations.filter(r => r.type === 'Risk-Based').length,
        regression: recommendations.filter(r => r.type === 'Regression').length,
        newFeature: recommendations.filter(r => r.type === 'New Feature').length,
        bugPattern: recommendations.filter(r => r.type === 'Bug Pattern').length,
      },
    };
  }, [recommendations]);

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'Critical':
        return 'bg-red-100 text-red-800 border-red-300 dark:bg-red-900 dark:text-red-200 dark:border-red-700';
      case 'High':
        return 'bg-orange-100 text-orange-800 border-orange-300 dark:bg-orange-900 dark:text-orange-200 dark:border-orange-700';
      case 'Medium':
        return 'bg-yellow-100 text-yellow-800 border-yellow-300 dark:bg-yellow-900 dark:text-yellow-200 dark:border-yellow-700';
      case 'Low':
        return 'bg-indigo-100 text-indigo-800 border-indigo-300 dark:bg-indigo-900 dark:text-indigo-200 dark:border-indigo-700';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-300 dark:bg-gray-700 dark:text-gray-200 dark:border-gray-600';
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'Coverage Gap':
        return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200';
      case 'Risk-Based':
        return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200';
      case 'Regression':
        return 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200';
      case 'New Feature':
        return 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200';
      case 'Bug Pattern':
        return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200';
      default:
        return 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200';
    }
  };

  const handlePreviewTestCases = (rec: Recommendation) => {
    // Get highest existing test case number
    const existingNumbers = testCases
      .map(tc => {
        const match = tc.id.match(/^TC-(\d+)$/);
        return match ? parseInt(match[1]) : 0;
      })
      .filter(n => n > 0);

    const nextNumber = existingNumbers.length > 0 ? Math.max(...existingNumbers) + 1 : 1;

    // Resolve moduleId from recommendation or linked story
    let resolvedModuleId = rec.moduleId;
    if (!resolvedModuleId && rec.storyId) {
      const linkedStory = stories.find(s => s.id === rec.storyId);
      if (linkedStory) {
        resolvedModuleId = linkedStory.moduleId;
      }
    }

    const newTestCases: TestCase[] = rec.suggestedTests.map((test, index) => {
      const testNumber = nextNumber + index;
      const testId = `TC-${String(testNumber).padStart(3, '0')}`;

      // Parse test suggestion to extract details
      const [testTypePrefix, ...titleParts] = test.split(':');
      const actualTitle = titleParts.length > 0 ? titleParts.join(':').trim() : test;

      // Generate basic steps and expected results from the test title
      const steps = [
        'Review test case details',
        'Execute test scenario',
        'Verify actual results match expected results',
        'Document any deviations'
      ];

      const expectedResults = [
        actualTitle,
        'No errors or unexpected behavior',
        'All acceptance criteria met'
      ];

      return {
        id: testId,
        title: actualTitle,
        description: `AI-generated test case from ${rec.type} recommendation (${rec.id}). Review and update as needed.`,
        type: rec.type === 'Regression' ? 'Regression' : rec.type === 'Risk-Based' ? 'Integration' : 'Functional',
        steps,
        expectedResults,
        linkedStory: rec.storyId,
        status: 'Not Run' as const, // Valid initial status
        priority: rec.priority === 'Critical' || rec.priority === 'High' ? 'High' : rec.priority === 'Medium' ? 'Medium' : 'Low',
        moduleId: resolvedModuleId,
      };
    });

    setPreviewTestCases(newTestCases);
    setShowPreviewModal(true);
  };

  const handleConfirmCreate = () => {
    setTestCases([...testCases, ...previewTestCases]);
    setShowPreviewModal(false);
    toast.success(
      <div>
        <div className="font-semibold">Created {previewTestCases.length} test cases</div>
        <div className="text-xs mt-1">IDs: {previewTestCases.map(tc => tc.id).join(', ')}</div>
        <div className="text-xs text-yellow-200 mt-1">⚠️ Status: Not Run - Edit test details in Test Cases tab before execution</div>
      </div>,
      { duration: 6000 }
    );
    setPreviewTestCases([]);
  };

  const handleViewDetails = (recId: string) => {
    setExpandedRecs(prev => {
      const newSet = new Set(prev);
      if (newSet.has(recId)) {
        newSet.delete(recId);
      } else {
        newSet.add(recId);
      }
      return newSet;
    });
  };

  const handleDismiss = (recId: string) => {
    setDismissedRecs(prev => new Set([...prev, recId]));
    toast.success('Recommendation dismissed');
  };

  return (
    <div className="w-full max-w-7xl mx-auto p-6">
      <div className="mb-8">
        <h1 className="text-3xl mb-2">AI-Powered Test Recommendations</h1>
        <p className="text-gray-600">Intelligent test prioritization based on risk, coverage gaps, and defect patterns</p>
      </div>

      {/* Metrics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
        <div className="bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-4">
          <div className="text-2xl mb-1 dark:text-white">{metrics.total}</div>
          <div className="text-sm text-gray-600 dark:text-gray-300">Total Recommendations</div>
        </div>
        <div className="bg-red-50 dark:bg-red-900 border border-red-200 dark:border-red-700 rounded-lg p-4">
          <div className="text-2xl mb-1 dark:text-white">{metrics.critical}</div>
          <div className="text-sm text-gray-600 dark:text-red-200">Critical Priority</div>
        </div>
        <div className="bg-orange-50 dark:bg-orange-900 border border-orange-200 dark:border-orange-700 rounded-lg p-4">
          <div className="text-2xl mb-1 dark:text-white">{metrics.high}</div>
          <div className="text-sm text-gray-600 dark:text-orange-200">High Priority</div>
        </div>
        <div className="bg-yellow-50 dark:bg-yellow-900 border border-yellow-200 dark:border-yellow-700 rounded-lg p-4">
          <div className="text-2xl mb-1 dark:text-white">{metrics.medium}</div>
          <div className="text-sm text-gray-600 dark:text-yellow-200">Medium Priority</div>
        </div>
        <div className="bg-indigo-50 dark:bg-indigo-900 border border-indigo-200 dark:border-indigo-700 rounded-lg p-4">
          <div className="text-2xl mb-1 dark:text-white">{metrics.low}</div>
          <div className="text-sm text-gray-600 dark:text-indigo-200">Low Priority</div>
        </div>
      </div>

      {/* Type Distribution */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
        <div className="bg-purple-50 dark:bg-purple-900 border border-purple-200 dark:border-purple-700 rounded-lg p-3">
          <div className="text-lg mb-1 dark:text-white">{metrics.byType.coverageGap}</div>
          <div className="text-xs text-gray-600 dark:text-purple-200">Coverage Gaps</div>
        </div>
        <div className="bg-red-50 dark:bg-red-900 border border-red-200 dark:border-red-700 rounded-lg p-3">
          <div className="text-lg mb-1 dark:text-white">{metrics.byType.riskBased}</div>
          <div className="text-xs text-gray-600 dark:text-red-200">Risk-Based</div>
        </div>
        <div className="bg-orange-50 dark:bg-orange-900 border border-orange-200 dark:border-orange-700 rounded-lg p-3">
          <div className="text-lg mb-1 dark:text-white">{metrics.byType.regression}</div>
          <div className="text-xs text-gray-600 dark:text-orange-200">Regression</div>
        </div>
        <div className="bg-indigo-50 dark:bg-indigo-900 border border-indigo-200 dark:border-indigo-700 rounded-lg p-3">
          <div className="text-lg mb-1 dark:text-white">{metrics.byType.newFeature}</div>
          <div className="text-xs text-gray-600 dark:text-indigo-200">New Feature</div>
        </div>
        <div className="bg-yellow-50 dark:bg-yellow-900 border border-yellow-200 dark:border-yellow-700 rounded-lg p-3">
          <div className="text-lg mb-1 dark:text-white">{metrics.byType.bugPattern}</div>
          <div className="text-xs text-gray-600 dark:text-yellow-200">Bug Patterns</div>
        </div>
      </div>

      {/* Filters */}
      <div className="mb-6 flex gap-4 items-center flex-wrap">
        <select
          value={filterPriority}
          onChange={(e) => setFilterPriority(e.target.value)}
          className="input"
        >
          <option value="all">All Priorities</option>
          <option value="Critical">Critical Only</option>
          <option value="High">High Only</option>
          <option value="Medium">Medium Only</option>
          <option value="Low">Low Only</option>
        </select>

        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
          className="input"
        >
          <option value="all">All Types</option>
          <option value="Coverage Gap">Coverage Gaps</option>
          <option value="Risk-Based">Risk-Based</option>
          <option value="Regression">Regression</option>
          <option value="New Feature">New Features</option>
          <option value="Bug Pattern">Bug Patterns</option>
        </select>

        <label className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
          <input
            type="checkbox"
            checked={showAutoOnly}
            onChange={(e) => setShowAutoOnly(e.target.checked)}
            className="rounded"
          />
          Auto-generated only
        </label>

        <div className="ml-auto text-sm text-gray-600 dark:text-gray-400">
          Showing {filteredRecommendations.length} of {recommendations.length} recommendations
        </div>
      </div>

      {/* Recommendations List */}
      <div className="space-y-4">
        {filteredRecommendations.map(rec => (
          <div key={rec.id} className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-6">
            <div className="flex items-start justify-between mb-4">
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <span className="text-lg font-medium text-gray-900 dark:text-white">{rec.id}</span>
                  <span className={`px-3 py-1 rounded-full text-xs border ${getPriorityColor(rec.priority)}`}>
                    {rec.priority} Priority
                  </span>
                  <span className={`px-3 py-1 rounded-full text-xs ${getTypeColor(rec.type)}`}>
                    {rec.type}
                  </span>
                  {rec.autoGenerated && (
                    <span className="px-3 py-1 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 rounded-full text-xs">
                      🤖 AI Generated
                    </span>
                  )}
                </div>
                {rec.storyId && (
                  <div className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                    Story:
                    <button
                      onClick={() => onNavigate?.('validator', rec.storyId)}
                      className="ml-1 font-medium text-indigo-600 dark:text-indigo-400 hover:underline cursor-pointer"
                    >
                      {rec.storyId}
                    </button>
                    <span> - {rec.storyTitle}</span>
                  </div>
                )}
                {rec.moduleId && (
                  <div className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                    Module:
                    <button
                      onClick={() => onNavigate?.('risk', rec.moduleId)}
                      className="ml-1 font-medium text-purple-600 dark:text-purple-400 hover:underline cursor-pointer"
                    >
                      {rec.moduleId}
                    </button>
                    <span> - {rec.moduleName}</span>
                  </div>
                )}
                <div className="text-sm text-gray-700 dark:text-gray-300 mb-3">{rec.reason}</div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400 text-right">
                <div className="mb-1">Estimated Effort:</div>
                <div className="font-medium">{rec.estimatedEffort}</div>
              </div>
            </div>

            <div className="bg-indigo-50 dark:bg-indigo-900 border border-indigo-200 dark:border-indigo-700 rounded p-4">
              <h4 className="text-sm font-medium text-gray-800 dark:text-indigo-100 mb-2">💡 Suggested Test Cases:</h4>
              <ul className="space-y-2">
                {rec.suggestedTests.map((test, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm text-gray-700 dark:text-indigo-200">
                    <span className="text-indigo-600 dark:text-indigo-400 flex-shrink-0">•</span>
                    <span>{test}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="mt-4 flex gap-2">
              <button
                type="button"
                className="btn btn-primary"
                onClick={() => handlePreviewTestCases(rec)}
              >
                Preview & Create Test Cases
              </button>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={() => handleViewDetails(rec.id)}
              >
                {expandedRecs.has(rec.id) ? 'Hide Details' : 'View Details'}
              </button>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={() => handleDismiss(rec.id)}
              >
                Dismiss
              </button>
            </div>

            {/* Expanded Details */}
            {expandedRecs.has(rec.id) && (
              <div className="mt-4 p-4 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg">
                <h4 className="text-sm font-semibold text-gray-900 dark:text-white mb-3">Additional Details</h4>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-600 dark:text-gray-400">Recommendation ID:</span>
                    <span className="font-medium text-gray-900 dark:text-white">{rec.id}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600 dark:text-gray-400">Auto-Generated:</span>
                    <span className="font-medium text-gray-900 dark:text-white">{rec.autoGenerated ? 'Yes' : 'No'}</span>
                  </div>
                  {rec.storyId && (
                    <div className="flex justify-between">
                      <span className="text-gray-600 dark:text-gray-400">Linked Story:</span>
                      <span className="font-medium text-gray-900 dark:text-white">{rec.storyId}</span>
                    </div>
                  )}
                  {rec.moduleId && (
                    <div className="flex justify-between">
                      <span className="text-gray-600 dark:text-gray-400">Linked Module:</span>
                      <span className="font-medium text-gray-900 dark:text-white">{rec.moduleId}</span>
                    </div>
                  )}
                  <div className="pt-2 border-t border-gray-200 dark:border-gray-700">
                    <span className="text-gray-600 dark:text-gray-400 block mb-1">Test Cases to Create:</span>
                    <span className="font-medium text-gray-900 dark:text-white">{rec.suggestedTests.length} test cases</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {filteredRecommendations.length === 0 && (
        <div className="bg-green-50 dark:bg-green-900 border border-green-200 dark:border-green-700 rounded-lg p-12 text-center">
          <span className="text-5xl mb-3 block">✅</span>
          <h3 className="text-xl text-gray-900 dark:text-white mb-2">No Recommendations Found</h3>
          <p className="text-gray-600 dark:text-gray-300">
            {filterPriority !== 'all' || filterType !== 'all'
              ? 'Try adjusting your filters to see more recommendations.'
              : 'Your test coverage is comprehensive! All critical areas are covered.'}
          </p>
        </div>
      )}

      {/* How It Works */}
      <div className="mt-8 bg-indigo-50 dark:bg-indigo-900 border border-indigo-200 dark:border-indigo-700 rounded-lg p-6">
        <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-3">🤖 How AI Recommendations Work</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-700 dark:text-indigo-200">
          <div>
            <h4 className="font-medium text-gray-900 dark:text-indigo-100 mb-2">Coverage Gap Analysis</h4>
            <p>Identifies stories without test cases and prioritizes based on development status and business impact.</p>
          </div>
          <div>
            <h4 className="font-medium text-gray-900 dark:text-indigo-100 mb-2">Risk-Based Prioritization</h4>
            <p>Uses historical defect frequency and business impact scores to recommend tests for high-risk modules first.</p>
          </div>
          <div>
            <h4 className="font-medium text-gray-900 dark:text-indigo-100 mb-2">Bug Pattern Detection</h4>
            <p>Analyzes defect history to identify areas with recurring bugs and suggests targeted regression tests.</p>
          </div>
        </div>
      </div>

      {/* Preview Modal */}
      {showPreviewModal && (
        <>
          <div className="fixed inset-0 bg-black bg-opacity-50 z-50" onClick={() => setShowPreviewModal(false)}></div>
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
              <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">Preview Test Cases</h2>
                <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                  Review AI-generated test cases before creation. You can edit them later in the Test Cases tab.
                </p>
              </div>

              <div className="flex-1 overflow-y-auto p-6">
                <div className="bg-yellow-50 dark:bg-yellow-900 border border-yellow-200 dark:border-yellow-700 rounded-lg p-4 mb-4">
                  <div className="flex items-start gap-2">
                    <span className="text-yellow-600 dark:text-yellow-400 text-xl">⚠️</span>
                    <div className="text-sm text-yellow-800 dark:text-yellow-200">
                      <div className="font-semibold mb-1">Important: Review Required</div>
                      <ul className="list-disc list-inside space-y-1">
                        <li>Test cases will be created with status: <strong>Not Run</strong></li>
                        <li>IDs are auto-generated sequentially (TC-001, TC-002, etc.)</li>
                        <li>Steps and expected results are placeholder templates</li>
                        <li><strong>Edit each test case</strong> in the Test Cases tab before execution</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="space-y-4">
                  {previewTestCases.map((tc) => (
                    <div key={tc.id} className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 bg-gray-50 dark:bg-gray-900">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <div className="flex items-center gap-2 mb-1">
                            <span className="font-mono text-sm font-semibold text-indigo-600 dark:text-indigo-400">{tc.id}</span>
                            <span className={`px-2 py-0.5 rounded text-xs ${
                              tc.priority === 'High' ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' :
                              tc.priority === 'Medium' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' :
                              'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200'
                            }`}>
                              {tc.priority}
                            </span>
                            <span className="px-2 py-0.5 bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200 rounded text-xs">
                              {tc.type}
                            </span>
                            <span className="px-2 py-0.5 bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300 rounded text-xs">
                              Not Run
                            </span>
                          </div>
                          <h4 className="font-medium text-gray-900 dark:text-white">{tc.title}</h4>
                          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">{tc.description}</p>
                          {tc.linkedStory && (
                            <div className="text-xs text-gray-500 dark:text-gray-500 mt-1">
                              Linked to: {tc.linkedStory}
                            </div>
                          )}
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-3 text-sm">
                        <div>
                          <div className="font-medium text-gray-700 dark:text-gray-300 mb-1">Steps ({tc.steps.length})</div>
                          <ul className="text-xs text-gray-600 dark:text-gray-400 space-y-0.5 list-disc list-inside">
                            {tc.steps.map((step, idx) => (
                              <li key={idx}>{step}</li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <div className="font-medium text-gray-700 dark:text-gray-300 mb-1">Expected Results ({tc.expectedResults.length})</div>
                          <ul className="text-xs text-gray-600 dark:text-gray-400 space-y-0.5 list-disc list-inside">
                            {tc.expectedResults.map((result, idx) => (
                              <li key={idx}>{result}</li>
                            ))}
                          </ul>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="px-6 py-4 border-t border-gray-200 dark:border-gray-700 flex justify-between items-center">
                <div className="text-sm text-gray-600 dark:text-gray-400">
                  {previewTestCases.length} test case{previewTestCases.length !== 1 ? 's' : ''} ready to create
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowPreviewModal(false)}
                    className="px-4 py-2 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleConfirmCreate}
                    className="px-6 py-2 bg-indigo-500 text-white rounded-lg hover:bg-indigo-600 transition-colors"
                  >
                    Create {previewTestCases.length} Test Case{previewTestCases.length !== 1 ? 's' : ''}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
